spring.application.name=ms-batch-producer
server.port=${SERVER_PORT:8080}
spring.config.import=optional:file:./config/sqlserver-local.properties
spring.datasource.url=${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=reto_db;encrypt=true;trustServerCertificate=true}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${MSSQL_SA_PASSWORD:Aa9!b629ee871b6f9dba1045b18a89364a4b}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=never
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/schema-sqlserver.sql,classpath:db/batch-sqlserver.sql
spring.sql.init.separator=^^^
app.batch.chunk-size=100
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=26MB
spring.servlet.multipart.file-size-threshold=0
app.upload.directory=./data/uploads
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
spring.kafka.producer.acks=all
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5
spring.kafka.producer.batch-size=32768
spring.kafka.producer.properties.linger.ms=5
spring.kafka.producer.compression-type=lz4
spring.kafka.producer.properties.max.block.ms=2000
spring.kafka.producer.properties.request.timeout.ms=5000
spring.kafka.producer.properties.delivery.timeout.ms=15000
spring.kafka.admin.fail-fast=false
spring.kafka.admin.properties.default.api.timeout.ms=5000
app.kafka.topic.record-ready=record-ready-topic-v2
app.kafka.partitions=3
app.kafka.replicas=1
app.outbox.enabled=true
app.outbox.batch-size=100
app.outbox.delay-ms=500
spring.kafka.admin.properties.request.timeout.ms=4000

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=60s
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.probes.enabled=true
