# Perfil de desarrollo local; conserva application.properties para H2.
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=reto_db;encrypt=true;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=Aa9!b629ee871b6f9dba1045b18a89364a4b
#spring.datasource.password=${MSSQL_SA_PASSWORD}
spring.h2.console.enabled=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.batch.jdbc.initialize-schema=always
spring.sql.init.mode=never
